name: TwistedConjugacyClone
version: "2.4.9"
license: "GPL-2.0-or-later"
date: 2025-04-12
description: |
    Computation with twisted conjugacy classes

authors:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

maintainers:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

GAP: ">= 4.13"

www: https://stertooy.github.io/TwistedConjugacyClone
readme: README.md
packageinfo: https://stertooy.github.io/TwistedConjugacyClone/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/stertooy/TwistedConjugacyClone/releases/download/v2.4.9/TwistedConjugacyClone-2.4.9.tar.gz
    - name: .zip,
      url: https://github.com/stertooy/TwistedConjugacyClone/releases/download/v2.4.9/TwistedConjugacyClone-2.4.9.zip,
    - name: .tar.bz2
      url: https://github.com/stertooy/TwistedConjugacyClone/releases/download/v2.4.9/TwistedConjugacyClone-2.4.9.tar.bz2

abstract: |
    
        The TwistedConjugacy package provides methods to calculate Reidemeister
        classes, numbers, spectra and zeta functions, as well as other methods
        related to homomorphisms, endomorphisms and automorphisms of groups.
        These methods are, for the most part, designed to be used with finite
        groups and polycyclically presented groups.

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    coincidence group, endomorphism, fixed point group, homomorphism, Reidemeister number, Reidemeister spectrum, Reidemeister zeta function, twisted conjugacy.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ter12</span>]   <b class='BibAuthor'>Tertooy, S.</b>,
     <i class='BibTitle'>TwistedConjugacyClone, Computation with twisted conjugacy classes,
             Version 2.4.9</i>
     (<span class='BibYear'>4-12</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://stertooy.github.io/TwistedConjugacyClone">https://stertooy.github.io/TwistedConjugacyClone</a></span>.
    </p>
    

bibtex: |
    @misc{ TwistedConjugacyClone,
      author =           {Tertooy, S.},
      title =            {{TwistedConjugacyClone},   {Computation  with  twisted
                          conjugacy classes}, {V}ersion 2.4.9},
      month =            {5\texttt{\symbol{45}}},
      year =             {4\texttt{\symbol{45}}12},
      note =             {GAP package},
      howpublished =     {\href
                          {https://stertooy.github.io/TwistedConjugacyClone}
                          {\texttt{https://stertooy.github.io/}\discretionary
                          {}{}{}\texttt{TwistedConjugacyClone}}},
      keywords =         {coincidence  group;  endomorphism;  fixed point group;
                          homomorphism;    Reidemeister   number;   Reidemeister
                          spectrum;    Reidemeister   zeta   function;   twisted
                          conjugacy},
      printedkey =       {Ter12}
    }

