name: TwistedConjugacyClone
version: "3.0.0"
license: "GPL-2.0-or-later"
date: 2025-07-21
description: |
    Computation with twisted conjugacy classes

authors:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

maintainers:
    - name: Sam Tertooy
      url: https://stertooy.github.io/

GAP: ">= 4.14"

suggested-pkgs:
    - name: "AutPGrp"
      version: "1.11"

www: https://stertooy.github.io/TwistedConjugacyClone
readme: README.md
packageinfo: https://stertooy.github.io/TwistedConjugacyClone/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/stertooy/TwistedConjugacyClone/releases/download/v3.0.0/TwistedConjugacyClone-3.0.0.tar.gz

abstract: |
    
        The TwistedConjugacy package provides methods for solving the twisted
        conjugacy problem (including the "search" and "multiple" variants) and for
        computing Reidemeister classes, numbers, spectra, and zeta functions. It
        also includes utility functions for working with (double) cosets, group
        homomorphisms, and group derivations.
    
        These methods are primarily designed for use with finite groups and with
        PcpGroups (finite or infinite) provided by the Polycyclic package.

doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    automorphism, coincidence group, coset, derivation, double coset, endomorphism, fixed point group, homomorphism, Reidemeister class, Reidemeister number, Reidemeister spectrum, Reidemeister zeta function, twisted conjugacy.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Ter25</span>]   <b class='BibAuthor'>Tertooy, S.</b>,
     <i class='BibTitle'>TwistedConjugacyClone, Computation with twisted conjugacy classes,
             Version 3.0.0</i>
     (<span class='BibYear'>2025</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://stertooy.github.io/TwistedConjugacyClone">https://stertooy.github.io/TwistedConjugacyClone</a></span>.
    </p>
    

bibtex: |
    @misc{ TwistedConjugacyClone,
      author =           {Tertooy, S.},
      title =            {{TwistedConjugacyClone},   {Computation  with  twisted
                          conjugacy classes}, {V}ersion 3.0.0},
      month =            {Jul},
      year =             {2025},
      note =             {GAP package},
      howpublished =     {\href
                          {https://stertooy.github.io/TwistedConjugacyClone}
                          {\texttt{https://stertooy.github.io/}\discretionary
                          {}{}{}\texttt{TwistedConjugacyClone}}},
      keywords =         {automorphism;  coincidence  group;  coset; derivation;
                          double   coset;   endomorphism;   fixed  point  group;
                          homomorphism; Reidemeister class; Reidemeister number;
                          Reidemeister  spectrum;  Reidemeister  zeta  function;
                          twisted conjugacy},
      printedkey =       {Ter25}
    }

