name: pkg_release_new
on:
  - workflow_dispatch
permissions: write-all

jobs:
  # The CI test job
  test:
    name: pkg_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: master
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/build-pkg-docs@v1
      - uses: stertooy/release-pkg@main
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
