name: Release Package
on:
  - workflow_dispatch
permissions: write-all

jobs:
  # The CI test job
  test:
    name: pkg_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: master
          GAP_PKGS_TO_BUILD: io profiling json crypting
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: true
      - uses: stertooy/release-pkg@experimental
        with:
          dry-run: true
