name: Release GAP Package (with container)
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Set to true to prevent actually making a release"
        type: boolean
        required: false
        default: false

permissions: write-all

jobs:
  release:
    name: "Release GAP Package"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stertooy/gda-image:master-full

    steps:
      - uses: actions/checkout@v4
      - uses: gap-actions/build-pkg-docs@no-leftover-files
        with:
          use-latex: true
      - uses: stertooy/release-pkg@update-features
      - name: "Fix container..."
        shell: bash
        run: |
          git config --global --add safe.directory $PWD
      - uses: stertooy/update-gh-pages@update-features
