---
name: Release Package
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Set to true to prevent actually making a release"
        type: boolean
        required: false
        default: false

permissions: write-all

jobs:
  release:
    name: "Release GAP Package"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stertooy/gda-image:tex-full

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build docs"
        uses: gap-actions/build-pkg-docs@v1.3.2
        
      - name: "Release GAP Package"
        uses: stertooy/release-pkg@fix

  pages:
    name: "Update GitHub pages with release"
    runs-on: ubuntu-latest
    needs: release
    container:
      image: ghcr.io/stertooy/gda-image:master-min
      
    steps:
      - name: "Fix container..."
        shell: bash
        run: |
          git config --global --add safe.directory $PWD
          sudo apt-get intall wget
    
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Update gh-pages"
        uses: stertooy/update-gh-pages@fix
        
