name: Release GAP Package (without container)
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Set to true to prevent actually making a release"
        type: boolean
        required: false
        default: false

permissions: write-all

jobs:
  release:
    name: "Release GAP Package"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: json
      - uses: gap-actions/build-pkg-docs@no-leftover-files
        with:
          use-latex: true
      - uses: stertooy/release-pkg@update-features
      - uses: stertooy/update-gh-pages@update-features
