name: Release Package
on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "set to true to prevent actually making a release"
        type: boolean
        required: false
        default: false

permissions: write-all

jobs:
  # The CI test job
  release:
    name: Release GAP Package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: gap-actions/setup-gap@v2
        with:
          GAPBRANCH: master
          GAP_PKGS_TO_BUILD: json
          
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: true
          
      - uses: stertooy/release-pkg@experimental
        with:
          dry-run: ${{ inputs.dry-run }}
          
      - name: "Upload the release"
        uses: actions/upload-artifact@v4
        with:
          name: "Release"
          path: ${{ env.ASSETS }}
          if-no-files-found: error
