name: Update GH-pages
on:
  workflow_dispatch:
  
permissions: write-all

jobs:
  # The CI test job
  update:
    name: Update GH pages
    runs-on: ubuntu-latest

    steps:
      - uses: gap-actions/setup-gap@v2
      - uses: stertooy/update-gh-pages@main
