name: Update Website

on:
  - workflow_dispatch
  - workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: gap-actions/setup-gap@v2
      - uses: stertooy/update-gh-pages@main
